### ISSUE TITLE
Atom superposition calculation fails at higher pairwise distance

### ISSUE THREAD

**Issue by RayHackett** [althonos/pyjess#2]
Specific matching Template/Molecule pairs fail to calculate a superposition. The superposition matrix contains NaN elements. The Determinant is NaN too. Consequently, calling Hit.atoms(transform=True) gives NaN x,y,z coordinates instead of the transformed atom coordinates.
Note that this behavior does not raise an Error.

Interestingly, this problem only seems to occurs at higher pairwise distances.
Tested on PDB structure https://www.rcsb.org/structure/1Y7W
and the attached template: 
[offending_template.txt](https://github.com/user-attachments/files/15526829/offending_template.txt)

parameters used: rmsd = 2, distance_cutoff=1.6, max_dynamic_distance=1.6, best_match=True

Any ideas why this may be happening?

**Comment by althonos** [comment]
I updated `Query.__next__` so that a superposition that contains `NaN` in the rotation matrix is never selected as the best match or returned, and that a warning is raised:

```console
UserWarning: Jess returned a superposition matrix with NaN values
```
